trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: prerequisite
  jobs:
  - job: InstallJavaAndMaven
    displayName: 'Install Java and Maven'
    steps:
    - script: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        sudo apt install -y maven
        echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
        echo "##vso[task.setvariable variable=MAVEN_HOME]/usr/share/maven"
        echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)/bin:$(MAVEN_HOME)/bin:$PATH"
      displayName: 'Install Java and Maven'

    - script: 'java -version'
      displayName: 'Check Java Version'

    - script: 'mvn -version'
      displayName: 'Check Maven Version'

- stage: BuildDockerImages
  jobs:
  - job: ContainerImages
    displayName: 'Build & Push Container Images'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'Azure subscription 1 (5e8944ac-d1ba-4b86-8315-eedd04e037d3)'
        azureContainerRegistry: '{"loginServer":"backecontainerregistry.azurecr.io", "id":"/subscriptions/5e8944ac-d1ba-4b86-8315-eedd04e037d3/resourceGroups/DemoRG/providers/Microsoft.ContainerRegistry/registries/BackeContainerRegistry"}'

    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'Azure subscription 1 (5e8944ac-d1ba-4b86-8315-eedd04e037d3)'
        azureContainerRegistry: '{"loginServer":"backecontainerregistry.azurecr.io", "id":"/subscriptions/5e8944ac-d1ba-4b86-8315-eedd04e037d3/resourceGroups/DemoRG/providers/Microsoft.ContainerRegistry/registries/BackeContainerRegistry"}'
        action: 'Push an image'
