trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: prerequisite
  jobs:
  - job: InstallJavaAndMaven
    displayName: 'Install Java and Maven'
    steps:
    - script: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        sudo apt install -y maven
        echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
        echo "##vso[task.setvariable variable=MAVEN_HOME]/usr/share/maven"
        echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)/bin:$(MAVEN_HOME)/bin:$PATH"
      displayName: 'Install Java and Maven'

    - script: 'java -version'
      displayName: 'Check Java Version'

    - script: 'mvn -version'
      displayName: 'Check Maven Version'

- stage: BuildDockerImages
  jobs:
  - job: ContainerImages
    displayName: 'Build & Push Container Images'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: Docker@2
      inputs:
        containerRegistry: 'Azure Container Registry Service Connection'
        repository: 'backecontainerregistry.azurecr.io/your-image-name'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
